bridge_url: ws://127.0.0.1:43001
bridge_http_url: http://127.0.0.1:43000
http_server_addr: 0.0.0.0:45000
metrics_endpoint: 0.0.0.0:9102
master_db_url: postgres://admin:admin123@localhost:7433/bitvm-operator
health_check_port: 43003
connect_retry_times: 1
bitcoin_confirms_threshold: 1
bitcoin_network: Regtest
mempool_url: unused
bitcoin_rpc: http://127.0.0.1:18443/wallet/benefactor
bitcoin_rpc_user: test
bitcoin_rpc_password: 1234
bridge_addresses:
  - 0x5FC8d32690cc91D4c39d9d3abcBD16989F875707  # evm
  - bbn17p9rzwnnfxcjp32un9ug7yhhzgtkhvl9jfksztgw5uh69wac2pgs6spw0g  # babylon
  - 0xfe0BB5287351408540E1ff646dEF342E412e9058  # bob
  - 0xfe0BB5287351408540E1ff646dEF342E412e9058  # monad
  - 0x27121685e3031c467a5142Eb22f2b712aA84bcF7  # zksync
  - 0x94367f2510CcAa6AE8c596CB9A9095E3B04fBBE0  # arbitrum
  - 0xfe0BB5287351408540E1ff646dEF342E412e9058  # optimism
  - 0x552747a0e293cdFfDC07348032579436bE8Ab2D3  # plume
  - 0x552747a0e293cdFfDC07348032579436bE8Ab2D3  # tatara
  - 0x6c86428C81025b4a78D065f70044e315E4C360c8  # hemi
  - Fdj7bMrz8u4ZLyHt3TAnbdqNxtNwQUtqEtgCM84SNWTG  # solana
redis_url: redis://127.0.0.1:6379
protocol_fee_address: "bcrt1p0p3rvwww0v9znrclp00uneq8ytre9kj922v8fxhnezm3mgsmn9usdxaefc"
feerate_rpc_url: unused

# Time lock in height
# connector one's time lock
connector_one_sequence: 6
# connector three's time lock
connector_three_sequence: 6
# connector burn's time lock
connector_burn_sequence: 12
# operator stake time lock
operator_stake_time_lock: 1

min_pegin_amount: 100000
max_pegin_amount: 300000000
min_pegout_amount: 100000
max_pegout_amount: 300000000
pegout_operator_fee_amount: 5000

# Side chains that the operator supports
side_chains:
  - "Anvil"
  # - "Holesky"
  # - "Solana"
  # - "Babylon"
  # - "BOB"
  # - "Monad"
  # - "ZKSYNC"
  # - "Arbitrum"
  # - "Optimism"
  # - "Plume"
  # - "Tatara"
  # - "Hemi"