bridge_url: wss://beta-bridge-api.fiammachain.io/ws
bridge_http_url: https://beta-bridge-api.fiammachain.io
http_server_addr: 0.0.0.0:55000
metrics_endpoint: 0.0.0.0:9102
master_db_url: postgres://admin:admin123@localhost:7433/bitvm-operator
health_check_port: 54003
connect_retry_times: 1
bitcoin_confirms_threshold: 1
bitcoin_network: Signet
mempool_url: https://blockbook-bitcoin-signet.fiammachain.io/api/v2
bitcoin_rpc: https://bitcoin-signet.fiammachain.io
bitcoin_rpc_user: fiamma
bitcoin_rpc_password: fiamma
bridge_addresses:
  - 0xeCC7EB129fCa72DE21BD065F7FA3Ab1aD400820D #holesky
  - 0x1dB460373869e23a3a04fa56a5405F27BfB67526 #monad
  - 0x9B3Eb09efd2C58f1BcABF47afDE0b44F6b63387e #plume
  - 0x36b3676D91B469e39d46A075Be789CbBA1e68146 #bsc
  - 0x938d19B736cc5C19C2613582844975789432ab5C #pharos
redis_url: redis://127.0.0.1:6379
protocol_fee_address: "tb1p2tge53kp4rxeqqq6s9jzq3ytvykecyaak5xs94ck6sgaaw2deycqs6dskr"
feerate_rpc_url: https://mempool.space/signet/api/v1/fees/recommended

# Time lock in height
# connector one's time lock
connector_one_sequence: 6
# connector three's time lock
connector_three_sequence: 6
# connector burn's time lock
connector_burn_sequence: 12
# operator stake time lock
operator_stake_time_lock: 1
min_pegin_amount: 100000
max_pegin_amount: 300000000
min_pegout_amount: 100000
max_pegout_amount: 300000000
pegout_operator_fee_amount: 5000

# Side chains that the operator supports
side_chains:
  # - chain: "Ethereum"
  - "Holesky"
  - "Monad"
  - "Plume"
  - "BSC"
  - "Pharos"