# signet.
# curl --user fiamma --data-binary '{"jsonrpc": "1.0", "id": "curltest", "method": "getblockcount", "params": []}' -H 'content-type: text/plain;' https://bitcoin-signet.fiammachain.io
http_url: https://bitcoin-signet.fiammachain.io
rpc_user: fiamma
rpc_password: fiamma
confirms_threshold: 1